---
- hosts: debian
  gather_facts: false

  vars:
    tmp_dir: /tmp/download

  tasks:

    - name: Download remote files into {{tmp_dir}}

      block:

        - name: Create {{tmp_dir}}
          file:
            path: "{{tmp_dir}}"
            state: directory

        - name: Download files
          get_url:
            url: http://localhost/{{item}}
            dest: "{{tmp_dir}}/{{item}}"
          with_items: [index.html, ttt.txt]

      rescue:

        - name: Cleanup {{tmp_dir}}
          file:
            path: "{{tmp_dir}}"
            state: absent

        - name: Fail execution
          fail: msg="error"

    - name: Should not be reached
      debug:
        msg: "Code reached, but should not because of previous fail in rescue!"

