---
- hosts: debian
  gather_facts: false

  tasks:

    - name: Determine space of root partition
      command: df -h /
      changed_when: false
      register: df_cmd

    - name: Debug
      debug:
        msg: "{{df_cmd.stdout_lines}}"
