---
- hosts: debian
  gather_facts: false

  tasks:

    - name: Copy server ttt.conf to target host
      copy:
        src: server/ttt.conf
        dest: /tmp
        owner: root
        group: root
        mode: 0600