---
- hosts: all
  gather_facts: false

  tasks:
    - debug: msg="Hello World!"
      tags: test

    # See ansible docs for more builtin modules:
    # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/index.html
    - name: Prints more messages
      ansible.builtin.debug:
        msg:
          - "Another message with 'Hello World!'"
          - "And another 'Hello World!'"

    - name: Another debug message
      debug:
        msg:
          - "Another message with 'Hello World!'"
          - "This time with short module name without module path..."
