# Variables are initialized by outside of the playbook e.g. group_vars/, host_vars/
---
- hosts: all
  gather_facts: false

  tasks:
    - name: Debug
      debug:
        msg: "Color: {{color}}, number: {{number}}"
